-- Insurance Reconciliation: remittance statements + line matching + payment provenance

CREATE TABLE IF NOT EXISTS insurance_statements (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name           VARCHAR(500) NOT NULL,
    storage_path        VARCHAR(1000),
    source_type         VARCHAR(20) NOT NULL,
    payer_name          VARCHAR(255),
    check_number        VARCHAR(100),
    statement_date      DATE,
    total_paid          NUMERIC(12, 2),
    status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    therapist_id        BIGINT,
    uploaded_by         BIGINT,
    uploaded_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    posted_by           BIGINT,
    posted_at           TIMESTAMPTZ,
    voided_by           BIGINT,
    voided_at           TIMESTAMPTZ,
    void_reason         TEXT,
    duplicate_signature VARCHAR(255),
    notes               TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_insurance_statement_status CHECK (status IN ('DRAFT', 'POSTED', 'VOIDED')),
    CONSTRAINT chk_insurance_statement_source CHECK (source_type IN ('PDF', 'EXCEL', 'CSV'))
);

CREATE TABLE IF NOT EXISTS insurance_statement_lines (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_id                BIGINT NOT NULL REFERENCES insurance_statements(id) ON DELETE CASCADE,
    line_number                 INT NOT NULL DEFAULT 0,
    service_date                DATE,
    client_name_raw             VARCHAR(255),
    cpt_code                    VARCHAR(40),
    billed_amount               NUMERIC(12, 2),
    allowed_amount              NUMERIC(12, 2),
    paid_amount                 NUMERIC(12, 2) NOT NULL DEFAULT 0,
    patient_responsibility      NUMERIC(12, 2),
    remark_code                 VARCHAR(100),
    match_status                VARCHAR(20) NOT NULL DEFAULT 'UNMATCHED',
    match_confidence            VARCHAR(20),
    matched_session_billing_id  BIGINT,
    matched_session_id          BIGINT,
    matched_client_id           BIGINT,
    posted_amount               NUMERIC(12, 2),
    skip_reason                 VARCHAR(255),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_insurance_line_match_status CHECK (
        match_status IN ('UNMATCHED', 'SUGGESTED', 'CONFIRMED', 'POSTED', 'SKIPPED', 'REVERSED')
    ),
    CONSTRAINT chk_insurance_line_match_confidence CHECK (
        match_confidence IS NULL OR match_confidence IN ('HIGH', 'MEDIUM', 'LOW', 'PARTIAL')
    )
);

CREATE INDEX IF NOT EXISTS idx_insurance_statements_status ON insurance_statements (status);
CREATE INDEX IF NOT EXISTS idx_insurance_statements_therapist ON insurance_statements (therapist_id);
CREATE INDEX IF NOT EXISTS idx_insurance_statements_dup_sig ON insurance_statements (duplicate_signature);
CREATE INDEX IF NOT EXISTS idx_insurance_statement_lines_statement ON insurance_statement_lines (statement_id);
CREATE INDEX IF NOT EXISTS idx_insurance_statement_lines_match ON insurance_statement_lines (match_status);
CREATE INDEX IF NOT EXISTS idx_insurance_statement_lines_billing ON insurance_statement_lines (matched_session_billing_id);

ALTER TABLE payment_transactions
    ADD COLUMN IF NOT EXISTS source_statement_id BIGINT,
    ADD COLUMN IF NOT EXISTS source_statement_line_id BIGINT,
    ADD COLUMN IF NOT EXISTS adopted_by_line_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_payment_txn_source_statement'
    ) THEN
        ALTER TABLE payment_transactions
            ADD CONSTRAINT fk_payment_txn_source_statement
            FOREIGN KEY (source_statement_id) REFERENCES insurance_statements(id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_payment_txn_source_statement_line'
    ) THEN
        ALTER TABLE payment_transactions
            ADD CONSTRAINT fk_payment_txn_source_statement_line
            FOREIGN KEY (source_statement_line_id) REFERENCES insurance_statement_lines(id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_payment_txn_adopted_by_line'
    ) THEN
        ALTER TABLE payment_transactions
            ADD CONSTRAINT fk_payment_txn_adopted_by_line
            FOREIGN KEY (adopted_by_line_id) REFERENCES insurance_statement_lines(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_payment_txn_source_statement ON payment_transactions (source_statement_id);
CREATE INDEX IF NOT EXISTS idx_payment_txn_source_line ON payment_transactions (source_statement_line_id);
CREATE INDEX IF NOT EXISTS idx_payment_txn_adopted_line ON payment_transactions (adopted_by_line_id);
