-- Therapist Payments: compensation ledger (pay rules + append-only earnings + payouts + allocations + adjustments)
-- Reads collected money from session_billing (never writes it); owns only these 6 tables.

CREATE TABLE IF NOT EXISTS therapist_pay_rules (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    therapist_id  BIGINT NOT NULL,
    service_id    BIGINT,
    pay_type      VARCHAR(20) NOT NULL,
    pay_value     NUMERIC(12, 2) NOT NULL,
    created_by    BIGINT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_pay_rule_type CHECK (pay_type IN ('percentage', 'fixed')),
    CONSTRAINT chk_pay_rule_value CHECK (pay_value >= 0)
);

-- One rule per scope (null service_id = therapist default rule). COALESCE folds null into 0.
CREATE UNIQUE INDEX IF NOT EXISTS uq_pay_rule
    ON therapist_pay_rules (therapist_id, COALESCE(service_id, 0));

CREATE TABLE IF NOT EXISTS therapist_earnings (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    therapist_id        BIGINT NOT NULL,
    session_billing_id  BIGINT NOT NULL,
    session_id          BIGINT,
    entry_type          VARCHAR(20) NOT NULL DEFAULT 'earning',
    amount_earned       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    collected_snapshot  NUMERIC(12, 2) NOT NULL DEFAULT 0,
    earned_date         DATE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_earning_entry_type CHECK (entry_type IN ('earning', 'adjustment'))
);

CREATE INDEX IF NOT EXISTS idx_therapist_earnings_therapist ON therapist_earnings (therapist_id);
CREATE INDEX IF NOT EXISTS idx_therapist_earnings_billing ON therapist_earnings (session_billing_id);
CREATE INDEX IF NOT EXISTS idx_therapist_earnings_earned_date ON therapist_earnings (earned_date);

CREATE TABLE IF NOT EXISTS therapist_payouts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    therapist_id     BIGINT NOT NULL,
    payout_type      VARCHAR(20) NOT NULL,
    amount           NUMERIC(12, 2) NOT NULL DEFAULT 0,
    payout_date      DATE,
    status           VARCHAR(20) NOT NULL DEFAULT 'paid',
    unapplied_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    reference        VARCHAR(255),
    notes            TEXT,
    paid_by          BIGINT,
    voided_by        BIGINT,
    voided_at        TIMESTAMPTZ,
    void_reason      TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_payout_type CHECK (payout_type IN ('itemized', 'lump')),
    CONSTRAINT chk_payout_status CHECK (status IN ('paid', 'voided'))
);

CREATE INDEX IF NOT EXISTS idx_therapist_payouts_therapist ON therapist_payouts (therapist_id);
CREATE INDEX IF NOT EXISTS idx_therapist_payouts_status ON therapist_payouts (status);

CREATE TABLE IF NOT EXISTS therapist_payout_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payout_id           BIGINT NOT NULL REFERENCES therapist_payouts(id) ON DELETE CASCADE,
    session_billing_id  BIGINT NOT NULL,
    session_id          BIGINT,
    amount              NUMERIC(12, 2) NOT NULL DEFAULT 0,
    earned_snapshot     NUMERIC(12, 2),
    collected_snapshot  NUMERIC(12, 2),
    pay_type            VARCHAR(20),
    pay_value           NUMERIC(12, 2),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_payout_item_pay_type CHECK (pay_type IS NULL OR pay_type IN ('percentage', 'fixed'))
);

-- Prevents double-settlement of a billing via itemized payouts (items are deleted on void, so uniqueness holds).
CREATE UNIQUE INDEX IF NOT EXISTS uq_payout_item_billing ON therapist_payout_items (session_billing_id);
CREATE INDEX IF NOT EXISTS idx_therapist_payout_items_payout ON therapist_payout_items (payout_id);

CREATE TABLE IF NOT EXISTS therapist_payment_allocations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payout_id           BIGINT NOT NULL REFERENCES therapist_payouts(id) ON DELETE CASCADE,
    session_billing_id  BIGINT NOT NULL,
    session_id          BIGINT,
    amount              NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_therapist_payment_allocations_payout ON therapist_payment_allocations (payout_id);
CREATE INDEX IF NOT EXISTS idx_therapist_payment_allocations_billing ON therapist_payment_allocations (session_billing_id);

CREATE TABLE IF NOT EXISTS therapist_adjustments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    therapist_id     BIGINT NOT NULL,
    adjustment_type  VARCHAR(20) NOT NULL,
    amount           NUMERIC(12, 2) NOT NULL DEFAULT 0,
    reason           TEXT,
    status           VARCHAR(20) NOT NULL DEFAULT 'active',
    effective_date   DATE,
    created_by       BIGINT,
    voided_by        BIGINT,
    voided_at        TIMESTAMPTZ,
    void_reason      TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_adjustment_type CHECK (adjustment_type IN ('bonus', 'deduction')),
    CONSTRAINT chk_adjustment_status CHECK (status IN ('active', 'voided'))
);

CREATE INDEX IF NOT EXISTS idx_therapist_adjustments_therapist ON therapist_adjustments (therapist_id);
CREATE INDEX IF NOT EXISTS idx_therapist_adjustments_status ON therapist_adjustments (status);
