-- TENANT
-- Backfill session transcript tables for tenants that already applied an older V1
-- (before session_transcripts / session_transcript_chunks were added to the baseline).
-- New tenants get these tables from V1__tenant_baseline.sql; this migration is a no-op for them.
-- Note: numbered V49 because V47/V48 are insurance reconciliation and therapist payments.

CREATE TABLE IF NOT EXISTS session_transcripts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    createdat timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    deleted_at timestamp(6) with time zone,
    is_deleted boolean NOT NULL DEFAULT false,
    updatedat timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    version bigint,
    session_id bigint NOT NULL,
    client_id bigint NOT NULL,
    uploader_id bigint NOT NULL,
    upload_id varchar(120) NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'recording',
    language varchar(20),
    translated_to_english boolean NOT NULL DEFAULT false,
    expected_chunks integer,
    received_chunks integer NOT NULL DEFAULT 0,
    duration_seconds integer,
    word_count integer,
    final_transcript TEXT,
    raw_content TEXT,
    finalized_at timestamp(6) with time zone,
    expires_at timestamp(6) with time zone,
    failure_reason TEXT,
    CONSTRAINT uk_session_transcripts_upload_id UNIQUE (upload_id)
);

CREATE TABLE IF NOT EXISTS session_transcript_chunks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    createdat timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    deleted_at timestamp(6) with time zone,
    is_deleted boolean NOT NULL DEFAULT false,
    updatedat timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    version bigint,
    transcript_id bigint NOT NULL,
    chunk_index integer NOT NULL,
    chunk_status varchar(20) NOT NULL,
    chunk_text TEXT,
    chunk_duration_seconds double precision,
    failure_reason TEXT,
    received_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_transcript_chunk_index UNIQUE (transcript_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_session_transcript_session ON session_transcripts (session_id);
CREATE INDEX IF NOT EXISTS idx_session_transcript_upload ON session_transcripts (upload_id);
CREATE INDEX IF NOT EXISTS idx_session_transcript_client ON session_transcripts (client_id);
CREATE INDEX IF NOT EXISTS idx_session_transcript_status ON session_transcripts (status);
CREATE INDEX IF NOT EXISTS idx_session_transcript_chunk_transcript ON session_transcript_chunks (transcript_id);
CREATE INDEX IF NOT EXISTS idx_session_transcript_chunk_index ON session_transcript_chunks (chunk_index);
CREATE INDEX IF NOT EXISTS idx_session_transcript_chunk_status ON session_transcript_chunks (chunk_status);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_transcripts_session'
    ) THEN
        ALTER TABLE session_transcripts
            ADD CONSTRAINT fk_session_transcripts_session
            FOREIGN KEY (session_id) REFERENCES sessions (id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_transcripts_client'
    ) THEN
        ALTER TABLE session_transcripts
            ADD CONSTRAINT fk_session_transcripts_client
            FOREIGN KEY (client_id) REFERENCES clients (id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_transcripts_uploader'
    ) THEN
        ALTER TABLE session_transcripts
            ADD CONSTRAINT fk_session_transcripts_uploader
            FOREIGN KEY (uploader_id) REFERENCES users (id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_transcript_chunks_transcript'
    ) THEN
        ALTER TABLE session_transcript_chunks
            ADD CONSTRAINT fk_session_transcript_chunks_transcript
            FOREIGN KEY (transcript_id) REFERENCES session_transcripts (id);
    END IF;
END $$;
