-- TENANT
-- Signed addenda for finalized session notes (immutable originals).

CREATE TABLE IF NOT EXISTS session_note_amendments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    createdat timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    deleted_at timestamp(6) with time zone,
    is_deleted boolean NOT NULL DEFAULT false,
    updatedat timestamp(6) with time zone NOT NULL,
    updated_by bigint NOT NULL,
    version bigint,
    session_note_id bigint NOT NULL,
    amendment_text TEXT NOT NULL,
    reason TEXT NOT NULL,
    created_by_user_id bigint NOT NULL,
    signed_at timestamp(6) with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_session_note_amendment_note
    ON session_note_amendments (session_note_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_note_amendments_note'
    ) THEN
        ALTER TABLE session_note_amendments
            ADD CONSTRAINT fk_session_note_amendments_note
            FOREIGN KEY (session_note_id) REFERENCES session_notes (id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_note_amendments_user'
    ) THEN
        ALTER TABLE session_note_amendments
            ADD CONSTRAINT fk_session_note_amendments_user
            FOREIGN KEY (created_by_user_id) REFERENCES users (id);
    END IF;
END $$;

COMMENT ON TABLE session_note_amendments IS
    'Signed addenda linked to immutable finalized session notes.';
