-- Name-token blind indexes for Client Page search (first/last name) without LIKE on encrypted PHI.
-- Exact full-name digests remain on clients.full_name_blind_idx; tokens enable single-token lookup.

CREATE TABLE IF NOT EXISTS client_name_blind_indexes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients (id) ON DELETE CASCADE,
    token_blind_idx BYTEA NOT NULL,
    token_ord INT NOT NULL,
    CONSTRAINT uq_client_name_token_ord UNIQUE (client_id, token_ord)
);

CREATE INDEX IF NOT EXISTS idx_client_name_token_blind
    ON client_name_blind_indexes (token_blind_idx);

CREATE INDEX IF NOT EXISTS idx_client_name_token_client
    ON client_name_blind_indexes (client_id);
