import fs from 'node:fs';
import path from 'node:path';
import { XMLParser } from 'fast-xml-parser';

const array = value => value == null ? [] : Array.isArray(value) ? value : [value];
const xml = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '', parseAttributeValue: false });
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function readJUnit(directory) {
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory).filter(f => /^TEST-.*\.xml$/.test(f)).flatMap(file => {
    const parsed = xml.parse(fs.readFileSync(path.join(directory, file), 'utf8'));
    return array(parsed.testsuite ?? parsed.testsuites?.testsuite).flatMap(suite => array(suite.testcase).map(test => ({
      name: `${test.classname ?? suite.name}#${test.name}`,
      status: test.failure !== undefined || test.error !== undefined ? 'failed' : test.skipped !== undefined ? 'skipped' : 'passed',
      seconds: Number(test.time || 0), evidence: path.join(directory, file),
    })));
  });
}

export function readPlaywright(file) {
  if (!fs.existsSync(file)) return [];
  const report = JSON.parse(fs.readFileSync(file, 'utf8'));
  const cases = [];
  function visit(suite) {
    for (const spec of suite.specs || []) for (const test of spec.tests || []) {
      const last = test.results?.at(-1);
      // An unexpected pass and a flaky retry are not a clean pass.
      const status = test.status === 'skipped' ? 'skipped' : test.status === 'expected' && last?.status === 'passed' ? 'passed' : 'failed';
      cases.push({ name: spec.title, status, seconds: (last?.duration || 0) / 1000, evidence: file });
    }
    (suite.suites || []).forEach(visit);
  }
  (report.suites || []).forEach(visit);
  if (report.errors?.length) cases.push({ name: 'Playwright runner errors', status: 'failed', seconds: 0, evidence: file });
  return cases;
}

export function buildReport(run, cases, catalog, discovery) {
  const totals = Object.fromEntries(['passed','failed','skipped'].map(status => [status, cases.filter(t => t.status === status).length]));
  const scope = catalog.map(item => {
    const evidence = cases.filter(test => (item.evidencePatterns || []).some(p => test.name.includes(p)));
    return { ...item, status: evidence.some(e => e.status === 'failed') ? 'failed' : evidence.some(e => e.status === 'passed') ? 'partial' : 'unverified',
      executedChecks: evidence.length, passingChecks: evidence.filter(e => e.status === 'passed').length };
  });
  const failed = run.stages.some(s => s.status === 'failed' || s.status === 'blocked') || totals.failed > 0 || totals.passed === 0;
  return { ...run, totals, result: failed ? 'FAILED' : 'IMPLEMENTED_CHECKS_PASSED', wholeAppVerified: false,
    scope, discovery: discovery ? { endpoints: discovery.endpoints.length, queryInputs: discovery.queryInputs.length, routes: discovery.routes.length,
      note: 'Static discovery, not execution coverage; aliases and non-filter parameters are included.' } : null,
    limitations: [
      'Partial/unverified scenario families remain. A passing run is not certification of every application feature.',
      'Browser fixture schema is generated by Hibernate and cloned for tenant isolation; it is not production Flyway migration evidence.',
      'Provider contract tests and disabled/mocked delivery are not live Zoom, Stripe, email/SMS or speech-recognition verification.',
      'Physical two-party audio capture, clinical output quality, restore drills and performance certification require separate evidence.',
    ], cases };
}

export function writeReport(directory, report) {
  fs.writeFileSync(path.join(directory, 'summary.json'), JSON.stringify(report, null, 2) + '\n');
  const relative = p => path.relative(directory, p).split(path.sep).map(encodeURIComponent).join('/');
  const stageRows = report.stages.map(s => `<tr><td>${escape(s.name)}</td><td>${escape(s.status)}</td><td>${s.exitCode ?? ''}</td><td>${s.log ? `<a href="${relative(s.log)}">log</a>` : escape(s.reason || '')}</td></tr>`).join('');
  const scopeRows = report.scope.map(s => `<tr><td>${escape(s.id)}</td><td>${escape(s.title)}</td><td>${escape(s.status)}</td><td>${s.passingChecks}/${s.executedChecks}</td></tr>`).join('');
  const testRows = report.cases.map(t => `<tr><td>${escape(t.name)}</td><td>${escape(t.status)}</td><td><a href="${relative(t.evidence)}">evidence</a></td></tr>`).join('');
  fs.writeFileSync(path.join(directory, 'index.html'), `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>SmartHub QA ${escape(report.id)}</title><style>body{font:15px system-ui;max-width:1200px;margin:32px auto;padding:0 20px;color:#172b36}table{border-collapse:collapse;width:100%;margin:20px 0}td,th{text-align:left;border-bottom:1px solid #ddd;padding:9px;vertical-align:top}code{overflow-wrap:anywhere}aside{background:#fff4d6;padding:16px}a{color:#065aa8}summary{cursor:pointer;font-weight:600}</style><h1>SmartHub QA: ${escape(report.result)}</h1><p>Run ${escape(report.id)} · ${escape(report.mode)} · ${escape(report.startedAt)}</p><aside><strong>Whole application coverage is incomplete.</strong> Passing implemented checks do not mark untested features as passed.</aside><p>${report.totals.passed} passed · ${report.totals.failed} failed · ${report.totals.skipped} skipped</p><p>Backend <code>${escape(report.backendRevision)}</code><br>Frontend <code>${escape(report.frontendRevision)}</code><br>Source fingerprint <code>${escape(report.sourceFingerprint)}</code></p><h2>Stages</h2><table><tr><th>Stage</th><th>Status</th><th>Exit</th><th>Evidence</th></tr>${stageRows}</table><p><a href="playwright/index.html">Browser HTML report and traces, when generated</a> · <a href="summary.json">Machine-readable report</a> · <a href="backend-build/site/jacoco/index.html">Backend code coverage, for full runs</a></p><h2>Scope ledger</h2><p>Evidence counts show related checks only. A partial family may have substantial missing scenarios.</p><table><tr><th>ID</th><th>Scenario family</th><th>Coverage status</th><th>Passing / executed related checks</th></tr>${scopeRows}</table><details><summary>Individual executed checks</summary><table>${testRows}</table></details><h2>Limitations</h2><ul>${report.limitations.map(s => `<li>${escape(s)}</li>`).join('')}</ul></html>`);
}
