ALTER TABLE public.organisations
    ADD COLUMN IF NOT EXISTS termination_effective_at TIMESTAMP WITH TIME ZONE;

CREATE INDEX IF NOT EXISTS idx_organisations_status_created_at
    ON public.organisations (status, created_at);

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS idx_organisations_name_trgm
    ON public.organisations USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_organisations_slug_trgm
    ON public.organisations USING gin (slug gin_trgm_ops);

CREATE TABLE IF NOT EXISTS public.platform_purge_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id BIGINT NOT NULL REFERENCES public.organisations(id) ON DELETE CASCADE,
    retention_days INTEGER NOT NULL,
    reason TEXT,
    status VARCHAR(20) NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE,
    error_message TEXT,
    created_by_auth_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_platform_purge_jobs_status_scheduled
    ON public.platform_purge_jobs (status, scheduled_at);
