CREATE TABLE IF NOT EXISTS public.org_stripe_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id BIGINT NOT NULL,
    connect_account_id VARCHAR(255),
    onboarding_status VARCHAR(30) NOT NULL DEFAULT 'NOT_CONNECTED',
    charges_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    payouts_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    details_submitted BOOLEAN NOT NULL DEFAULT FALSE,
    country VARCHAR(2),
    default_currency VARCHAR(3),
    last_synced_at TIMESTAMPTZ,
    disabled_reason TEXT,
    oauth_state VARCHAR(255),
    oauth_state_expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_org_stripe_accounts_org
        FOREIGN KEY (organisation_id) REFERENCES public.organisations(id) ON DELETE CASCADE,
    CONSTRAINT uq_org_stripe_accounts_org UNIQUE (organisation_id),
    CONSTRAINT uq_org_stripe_accounts_connect UNIQUE (connect_account_id)
);

CREATE INDEX IF NOT EXISTS idx_org_stripe_accounts_org ON public.org_stripe_accounts (organisation_id);
CREATE INDEX IF NOT EXISTS idx_org_stripe_accounts_connect ON public.org_stripe_accounts (connect_account_id);

ALTER TABLE public.stripe_webhook_events
    ADD COLUMN IF NOT EXISTS context_key VARCHAR(255) NOT NULL DEFAULT 'default';

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'stripe_webhook_events_event_id_key'
          AND conrelid = 'public.stripe_webhook_events'::regclass
    ) THEN
        ALTER TABLE public.stripe_webhook_events
            DROP CONSTRAINT stripe_webhook_events_event_id_key;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_stripe_webhook_events_event_context'
          AND conrelid = 'public.stripe_webhook_events'::regclass
    ) THEN
        ALTER TABLE public.stripe_webhook_events
            ADD CONSTRAINT uq_stripe_webhook_events_event_context UNIQUE (event_id, context_key);
    END IF;
END $$;
