CREATE TABLE IF NOT EXISTS public.org_feature_overrides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id BIGINT NOT NULL,
    feature_key VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    usage_limit INTEGER NULL,
    createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by BIGINT NOT NULL DEFAULT 0,
    updated_by BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT uq_org_feature_overrides_org_feature UNIQUE (organisation_id, feature_key),
    CONSTRAINT fk_org_feature_overrides_organisation
        FOREIGN KEY (organisation_id) REFERENCES public.organisations(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_org_feature_overrides_org
    ON public.org_feature_overrides (organisation_id);

CREATE INDEX IF NOT EXISTS idx_org_feature_overrides_org_feature
    ON public.org_feature_overrides (organisation_id, feature_key);

ALTER TABLE public.feature_rollout_rules
    ADD COLUMN IF NOT EXISTS target_id BIGINT;

DO $$
BEGIN
    UPDATE public.feature_rollout_rules
    SET target_id = NULLIF(regexp_replace(target_key, '[^0-9]', '', 'g'), '')::BIGINT
    WHERE target_id IS NULL
      AND target_key IS NOT NULL
      AND target_key ~ '^[0-9]+$';
EXCEPTION
    WHEN OTHERS THEN
        -- Backfill is best effort only.
        NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_feature_rollout_scope_target_id
    ON public.feature_rollout_rules (organisation_id, scope, target_id);
