ALTER TABLE public.app_features
    ADD COLUMN IF NOT EXISTS scope VARCHAR(20) NOT NULL DEFAULT 'TENANT',
    ADD COLUMN IF NOT EXISTS feature_type VARCHAR(20) NOT NULL DEFAULT 'CORE',
    ADD COLUMN IF NOT EXISTS default_enabled BOOLEAN NOT NULL DEFAULT FALSE;
