CREATE TABLE IF NOT EXISTS public.plan_pricing_tiers (
    id bigint NOT NULL,
    plan_id bigint NOT NULL,
    min_therapists int NOT NULL,
    max_therapists int NOT NULL,
    price_per_therapist_usd numeric(12,2) NOT NULL,
    included_supervisors int NOT NULL,
    included_clients int NOT NULL,
    createdat timestamp with time zone DEFAULT now() NOT NULL,
    updatedat timestamp with time zone DEFAULT now() NOT NULL,
    created_by bigint DEFAULT 0 NOT NULL,
    updated_by bigint DEFAULT 0 NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone
);

ALTER TABLE public.plan_pricing_tiers
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.plan_pricing_tiers_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'plan_pricing_tiers_pkey'
    ) THEN
        ALTER TABLE public.plan_pricing_tiers
            ADD CONSTRAINT plan_pricing_tiers_pkey PRIMARY KEY (id);
    END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_plan_pricing_tiers_plan ON public.plan_pricing_tiers (plan_id);

ALTER TABLE public.plan_pricing_tiers
    ADD CONSTRAINT plan_pricing_tiers_plan_id_fkey FOREIGN KEY (plan_id)
    REFERENCES public.subscription_plans(id);
