CREATE TABLE IF NOT EXISTS public.platform_dashboard_tier_aliases (
    id bigint NOT NULL,
    tier_name varchar(30) NOT NULL,
    plan_code varchar(100) NOT NULL,
    createdat timestamp with time zone DEFAULT now() NOT NULL,
    updatedat timestamp with time zone DEFAULT now() NOT NULL,
    created_by bigint DEFAULT 0 NOT NULL,
    updated_by bigint DEFAULT 0 NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp with time zone
);

ALTER TABLE public.platform_dashboard_tier_aliases
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.platform_dashboard_tier_aliases_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'platform_dashboard_tier_aliases_pkey'
    ) THEN
        ALTER TABLE public.platform_dashboard_tier_aliases
            ADD CONSTRAINT platform_dashboard_tier_aliases_pkey PRIMARY KEY (id);
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_platform_dashboard_tier_aliases_tier_plan'
    ) THEN
        ALTER TABLE public.platform_dashboard_tier_aliases
            ADD CONSTRAINT uk_platform_dashboard_tier_aliases_tier_plan
            UNIQUE (tier_name, plan_code);
    END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_platform_dashboard_tier_aliases_tier
    ON public.platform_dashboard_tier_aliases (tier_name);

CREATE INDEX IF NOT EXISTS idx_platform_dashboard_tier_aliases_plan
    ON public.platform_dashboard_tier_aliases (plan_code);

INSERT INTO public.platform_dashboard_tier_aliases (tier_name, plan_code)
VALUES
    ('Enterprise', 'ENTERPRISE'),
    ('Pro', 'PRO'),
    ('Pro', 'PROFESSIONAL'),
    ('Growth', 'GROWTH'),
    ('Starter', 'STARTER'),
    ('Starter', 'FREE'),
    ('Starter', 'BASIC')
ON CONFLICT (tier_name, plan_code) DO NOTHING;
