DO $$
DECLARE
    rec RECORD;
BEGIN
    FOR rec IN
        SELECT DISTINCT o.schema_name
        FROM public.organisations o
        WHERE o.schema_name IS NOT NULL
          AND btrim(o.schema_name) <> ''
          AND lower(o.schema_name) <> 'public'
    LOOP
        EXECUTE format($f$
            CREATE TABLE IF NOT EXISTS %I.notification_action_metadata (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                createdat TIMESTAMPTZ NOT NULL DEFAULT now(),
                updatedat TIMESTAMPTZ NOT NULL DEFAULT now(),
                created_by BIGINT NOT NULL DEFAULT 0,
                updated_by BIGINT NOT NULL DEFAULT 0,
                version BIGINT DEFAULT 0,
                is_deleted BOOLEAN NOT NULL DEFAULT false,
                deleted_at TIMESTAMPTZ,
                related_entity_type VARCHAR(50) NOT NULL,
                action_url_template VARCHAR(500) NOT NULL,
                default_action_label VARCHAR(100) NOT NULL,
                example_action_url VARCHAR(500),
                sort_order INTEGER DEFAULT 0,
                is_active BOOLEAN NOT NULL DEFAULT true,
                CONSTRAINT uk_notification_action_metadata_entity_type UNIQUE (related_entity_type)
            )
        $f$, rec.schema_name);

        EXECUTE format('CREATE INDEX IF NOT EXISTS idx_notification_action_metadata_sort ON %I.notification_action_metadata (sort_order)', rec.schema_name);
        EXECUTE format('CREATE INDEX IF NOT EXISTS idx_notification_action_metadata_active ON %I.notification_action_metadata (is_active)', rec.schema_name);

        EXECUTE format($f$
            INSERT INTO %I.notification_action_metadata
                (related_entity_type, action_url_template, default_action_label, example_action_url, sort_order, is_active)
            VALUES
                ('session', '/sessions/{id}', 'View session', '/sessions/123', 10, true),
                ('client', '/clients/{id}', 'View client', '/clients/456', 20, true),
                ('task', '/tasks/{id}', 'View task', '/tasks/654', 30, true),
                ('checklist', '/checklists/{id}', 'View checklist', '/checklists/222', 40, true),
                ('billing', '/billing/{id}', 'View billing', '/billing/789', 50, true),
                ('form', '/forms/{id}', 'View form', '/forms/333', 60, true),
                ('document', '/documents/{id}', 'View document', '/documents/987', 70, true),
                ('assessment', '/assessments/{id}', 'View assessment', '/assessments/321', 80, true),
                ('user', '/users/{id}', 'View profile', '/users/111', 90, true),
                ('room', '/rooms/{id}', 'View room', '/rooms/444', 100, true),
                ('general', '/notifications', 'View details', '/notifications', 110, true)
            ON CONFLICT (related_entity_type) DO NOTHING
        $f$, rec.schema_name);
    END LOOP;
END $$;

