CREATE TABLE IF NOT EXISTS public.auth_refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    createdat timestamp with time zone NOT NULL DEFAULT now(),
    created_by bigint NOT NULL DEFAULT 0,
    deleted_at timestamp with time zone,
    is_deleted boolean NOT NULL DEFAULT false,
    updatedat timestamp with time zone NOT NULL DEFAULT now(),
    updated_by bigint NOT NULL DEFAULT 0,
    version bigint,
    auth_id bigint NOT NULL REFERENCES public.auth_identities(id),
    family_id varchar(64) NOT NULL,
    token_hash varchar(64) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked boolean NOT NULL DEFAULT false,
    revoked_at timestamp with time zone,
    replaced_by_hash varchar(64),
    reuse_detected boolean NOT NULL DEFAULT false,
    ip_address varchar(50),
    user_agent text,
    CONSTRAINT uq_auth_refresh_tokens_hash UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS idx_auth_refresh_tokens_auth_id
    ON public.auth_refresh_tokens (auth_id);

CREATE INDEX IF NOT EXISTS idx_auth_refresh_tokens_family_id
    ON public.auth_refresh_tokens (family_id);

CREATE INDEX IF NOT EXISTS idx_auth_refresh_tokens_expires
    ON public.auth_refresh_tokens (expires_at);
