CREATE TABLE IF NOT EXISTS public.platform_phi_encryption_backfill_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_name varchar(100) NOT NULL,
    table_name varchar(100) NOT NULL,
    column_name varchar(100) NOT NULL,
    pk_column varchar(50) NOT NULL DEFAULT 'id',
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    last_processed_id bigint NOT NULL DEFAULT 0,
    processed_count bigint NOT NULL DEFAULT 0,
    error_count bigint NOT NULL DEFAULT 0,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_phi_backfill_schema_table_column UNIQUE (schema_name, table_name, column_name)
);

CREATE INDEX IF NOT EXISTS idx_phi_backfill_status_updated
    ON public.platform_phi_encryption_backfill_jobs (status, updated_at);

COMMENT ON TABLE public.platform_phi_encryption_backfill_jobs IS
    'Restartable platform jobs for encrypting legacy plaintext PHI columns (ops-controlled).';
