-- Platform CMS tables for marketing landing page (Phase 1).
-- Isolated to public schema — no tenant impact.

CREATE TABLE IF NOT EXISTS cms_global_settings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content         JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_by_auth_id BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Seed a single row so GET always finds settings.
INSERT INTO cms_global_settings (content)
SELECT jsonb_build_object(
    'Site_Name', 'TherapyFlow',
    'Landing_Domain', 'https://therapyflow.pro',
    'LearningHub_Domain', 'https://learninghub.therapyflow.pro',
    'Twitter_Handle', NULL,
    'Organization_Name', 'TherapyFlow',
    'Organization_URL', 'https://therapyflow.pro',
    'Google_Site_Verification', NULL,
    'Default_OG_Image', NULL,
    'Organization_Logo', NULL,
    'Landing_SEO', NULL,
    'LearningHub_SEO', NULL
)
WHERE NOT EXISTS (SELECT 1 FROM cms_global_settings);

CREATE TABLE IF NOT EXISTS cms_landing_page (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_content       JSONB NOT NULL DEFAULT '{}'::jsonb,
    published_content   JSONB,
    published_at        TIMESTAMPTZ,
    updated_by_auth_id  BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Seed a single landing page row.
INSERT INTO cms_landing_page (draft_content)
SELECT '{}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM cms_landing_page);

CREATE TABLE IF NOT EXISTS cms_media_asset (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_key     VARCHAR(512) NOT NULL,
    public_url      VARCHAR(1024) NOT NULL,
    filename        VARCHAR(255) NOT NULL,
    mime_type       VARCHAR(128),
    size_bytes      BIGINT,
    alt_text        VARCHAR(255),
    width           INTEGER,
    height          INTEGER,
    uploaded_by_auth_id BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cms_media_asset_created_at ON cms_media_asset (created_at DESC);
