-- Phase 2: Learning Hub articles (platform schema only).

CREATE TABLE IF NOT EXISTS cms_learning_hub_article (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                VARCHAR(220) NOT NULL,
    title               VARCHAR(200) NOT NULL,
    draft_content       JSONB NOT NULL DEFAULT '{}'::jsonb,
    published_content   JSONB,
    published_at        TIMESTAMPTZ,
    sort_order          INTEGER NOT NULL DEFAULT 0,
    chapter             VARCHAR(200),
    section_name        VARCHAR(200),
    is_featured         BOOLEAN NOT NULL DEFAULT FALSE,
    is_published        BOOLEAN NOT NULL DEFAULT FALSE,
    updated_by_auth_id  BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_cms_learning_hub_article_slug UNIQUE (slug)
);

CREATE INDEX IF NOT EXISTS idx_cms_lh_article_order
    ON cms_learning_hub_article (sort_order ASC, id ASC);

CREATE INDEX IF NOT EXISTS idx_cms_lh_article_published
    ON cms_learning_hub_article (is_published, sort_order ASC);
