-- Restartable platform jobs for Approach C blind-index digest backfill (ops-controlled).
CREATE TABLE IF NOT EXISTS public.platform_phi_blind_index_backfill_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_name varchar(100) NOT NULL,
    organisation_id bigint NOT NULL,
    job_kind varchar(40) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    last_processed_id bigint NOT NULL DEFAULT 0,
    processed_count bigint NOT NULL DEFAULT 0,
    error_count bigint NOT NULL DEFAULT 0,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_phi_blind_backfill_schema_kind UNIQUE (schema_name, job_kind)
);

CREATE INDEX IF NOT EXISTS idx_phi_blind_backfill_status_updated
    ON public.platform_phi_blind_index_backfill_jobs (status, updated_at);

COMMENT ON TABLE public.platform_phi_blind_index_backfill_jobs IS
    'Restartable jobs to populate clients/client_contacts *_blind_idx digests and optionally encrypt MRN / re-encrypt v2d→v2.';
