-- Platform audit immutability (WORM) and tenant audit archive before schema drop.

CREATE TABLE IF NOT EXISTS public.tenant_audit_archive (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id bigint NOT NULL,
    tenant_schema character varying(255) NOT NULL,
    archived_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    row_count bigint NOT NULL DEFAULT 0,
    payload jsonb NOT NULL DEFAULT '[]'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_tenant_audit_archive_org
    ON public.tenant_audit_archive (org_id);

CREATE INDEX IF NOT EXISTS idx_tenant_audit_archive_schema
    ON public.tenant_audit_archive (tenant_schema);

COMMENT ON TABLE public.tenant_audit_archive IS
    'Archived tenant audit_logs rows captured before organisation purge / schema drop';

CREATE OR REPLACE FUNCTION platform_audit_logs_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'platform_audit_logs is append-only'
        USING ERRCODE = '55000';
END
$$;

DROP TRIGGER IF EXISTS trg_platform_audit_logs_reject_mutation ON public.platform_audit_logs;
CREATE TRIGGER trg_platform_audit_logs_reject_mutation
    BEFORE UPDATE OR DELETE ON public.platform_audit_logs
    FOR EACH ROW
    EXECUTE FUNCTION platform_audit_logs_reject_mutation();

COMMENT ON TABLE public.platform_audit_logs IS
    'Append-only audit trail for platform super-admin actions (UPDATE/DELETE rejected by trigger)';
