-- PLATFORM
-- ClientHubAI migration and synchronization control tables.
--
-- These tables are intentionally in public because a single V1 source is mapped
-- into one destination organisation/tenant schema. They store identifiers,
-- checksums, counts, and redacted errors only; no PHI payloads belong here.

CREATE TABLE IF NOT EXISTS public.clienthub_migration_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id BIGINT NOT NULL REFERENCES public.organisations(id),
    source_system VARCHAR(50) NOT NULL DEFAULT 'ClientHubAI',
    mode VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    source_schema_fingerprint_sha256 VARCHAR(64),
    source_counts JSONB,
    target_counts JSONB,
    totals JSONB,
    error_code VARCHAR(80),
    error_message TEXT,
    created_by BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT chk_clienthub_migration_runs_mode
        CHECK (mode IN ('DRY_RUN', 'EXECUTE')),
    CONSTRAINT chk_clienthub_migration_runs_status
        CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_clienthub_migration_runs_org_started
    ON public.clienthub_migration_runs (organisation_id, started_at DESC);

CREATE TABLE IF NOT EXISTS public.clienthub_legacy_id_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id BIGINT NOT NULL REFERENCES public.organisations(id),
    source_system VARCHAR(50) NOT NULL DEFAULT 'ClientHubAI',
    entity_name VARCHAR(120) NOT NULL,
    source_id VARCHAR(120) NOT NULL,
    target_schema VARCHAR(63) NOT NULL,
    target_table VARCHAR(120) NOT NULL,
    target_id BIGINT NOT NULL,
    source_checksum_sha256 VARCHAR(64),
    target_checksum_sha256 VARCHAR(64),
    first_seen_run_id BIGINT REFERENCES public.clienthub_migration_runs(id),
    last_seen_run_id BIGINT REFERENCES public.clienthub_migration_runs(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_clienthub_legacy_id_mapping
        UNIQUE (organisation_id, source_system, entity_name, source_id),
    CONSTRAINT uq_clienthub_target_mapping
        UNIQUE (organisation_id, target_schema, target_table, target_id)
);

CREATE INDEX IF NOT EXISTS idx_clienthub_legacy_id_mappings_target
    ON public.clienthub_legacy_id_mappings (target_schema, target_table, target_id);

CREATE TABLE IF NOT EXISTS public.clienthub_migration_record_outcomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL REFERENCES public.clienthub_migration_runs(id) ON DELETE CASCADE,
    organisation_id BIGINT NOT NULL REFERENCES public.organisations(id),
    entity_name VARCHAR(120) NOT NULL,
    source_id VARCHAR(120) NOT NULL,
    action VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    target_table VARCHAR(120),
    target_id BIGINT,
    checksum_sha256 VARCHAR(64),
    error_code VARCHAR(80),
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_clienthub_record_outcomes_action
        CHECK (action IN ('NO_OP', 'CREATE', 'UPDATE', 'BLOCKED', 'SKIPPED')),
    CONSTRAINT chk_clienthub_record_outcomes_status
        CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'BLOCKED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_clienthub_record_outcome_per_run
    ON public.clienthub_migration_record_outcomes (run_id, entity_name, source_id);

CREATE TABLE IF NOT EXISTS public.clienthub_sync_checkpoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id BIGINT NOT NULL REFERENCES public.organisations(id),
    source_system VARCHAR(50) NOT NULL DEFAULT 'ClientHubAI',
    entity_name VARCHAR(120) NOT NULL,
    cursor_value TEXT,
    cursor_checksum_sha256 VARCHAR(64),
    last_successful_sync_at TIMESTAMPTZ,
    last_attempted_sync_at TIMESTAMPTZ,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    failure_count INTEGER NOT NULL DEFAULT 0,
    last_error_code VARCHAR(80),
    last_error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_clienthub_sync_checkpoint
        UNIQUE (organisation_id, source_system, entity_name),
    CONSTRAINT chk_clienthub_sync_checkpoint_status
        CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'PAUSED'))
);

CREATE TABLE IF NOT EXISTS public.clienthub_sync_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id BIGINT NOT NULL REFERENCES public.organisations(id),
    source_system VARCHAR(50) NOT NULL DEFAULT 'ClientHubAI',
    entity_name VARCHAR(120) NOT NULL,
    source_id VARCHAR(120) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ,
    source_checksum_sha256 VARCHAR(64),
    target_table VARCHAR(120),
    target_id BIGINT,
    error_code VARCHAR(80),
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_clienthub_sync_event_idempotency
        UNIQUE (organisation_id, idempotency_key),
    CONSTRAINT chk_clienthub_sync_events_event_type
        CHECK (event_type IN ('CREATE', 'UPDATE', 'DELETE', 'ARCHIVE', 'RESTORE')),
    CONSTRAINT chk_clienthub_sync_events_status
        CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'DEAD_LETTER'))
);

CREATE INDEX IF NOT EXISTS idx_clienthub_sync_events_due
    ON public.clienthub_sync_events (status, next_attempt_at, created_at);

COMMENT ON TABLE public.clienthub_migration_runs IS
    'ClientHubAI migration run summaries; counts/checksums only, no PHI payloads.';
COMMENT ON TABLE public.clienthub_legacy_id_mappings IS
    'Stable V1 source id to destination tenant row mapping for idempotent reruns.';
COMMENT ON TABLE public.clienthub_migration_record_outcomes IS
    'Per-record migration decisions and redacted failures.';
COMMENT ON TABLE public.clienthub_sync_checkpoints IS
    'Incremental one-way sync cursors from ClientHubAI into a tenant.';
COMMENT ON TABLE public.clienthub_sync_events IS
    'Idempotent sync work queue with retry/dead-letter state; no PHI payloads.';
